sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.1
  - jruby-9.1.17.0
install:
  - gem install bundler -v 1.16.2
  - bundle install --jobs=3 --retry=3 --path vendor/bundle
script: bundle exec rake test
